version: '3.8'
services:
  # BACKEND
  lumen:
    image: lumen-backend
    build:
      context: ./lumen-backend/
      dockerfile: ../docker-images/lumen-backend/Dockerfile
    depends_on:
      - mariadb
    ports:
      - '${LUMEN_PORT:-8080}:8080'
    environment:
      WAIT_HOSTS: mariadb:3306
      APP_ENV: production
      APP_DEBUG: 0
      DB_CONNECTION: mysql
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_DATABASE: '${LUMEN_DB_DATABASE:-awp_employee_happiness}'
      DB_USERNAME: '${LUMEN_DB_USERNAME:-user}'
      DB_PASSWORD: '${LUMEN_DB_PASSWORD:-password}'
    command: php -S 0.0.0.0:8080 public/index.php

  # FRONTEND
  vue:
    image: vue-frontend
    build: 
      context: ./vue-frontend/
      dockerfile: ../docker-images/vue-frontend/Dockerfile
      args:
        VITE_API_BASE_URL: 'http://${LUMEN_HOST:-localhost}:${LUMEN_PORT:-8080}'
    ports:
      - '${APP_PORT:-3000}:80'
    command: nginx -g "daemon off;"

  # DATABASE
  mariadb:
    image: "mariadb:latest"
    volumes:
     - awp_db_data:/var/lib/mysql
     - ./lumen-backend/database/schema/:/docker-entrypoint-initdb.d/:ro
    ports:
       - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 1
      MARIADB_DATABASE: '${LUMEN_DB_DATABASE:-awp_employee_happiness}'
      MARIADB_USER: '${LUMEN_DB_USERNAME:-user}'
      MARIADB_PASSWORD: '${LUMEN_DB_PASSWORD:-password}'

volumes:
  awp_db_data: