version: '3.8'
services:
  # BACKEND
  lumen-backend:
    image: lumen-backend
    build:
      context: ./api/
      dockerfile: ../docker-images/lumen-backend/Dockerfile
    depends_on:
      - mariadb
    ports:
      - '${LUMEN_PORT:-8080}:8080'
    environment:
      WAIT_HOSTS: mariadb:3306
      APP_ENV: production
      APP_DEBUG: 0
      DB_CONNECTION: mysql
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_DATABASE: '${LUMEN_DB_DATABASE:-mydb}'
      DB_USERNAME: '${LUMEN_DB_USERNAME:-user}'
      DB_PASSWORD: '${LUMEN_DB_PASSWORD:-password}'
    command: php -S 0.0.0.0:8080 public/index.php
    networks:
      - mynetwork

  # FRONTEND
  vue-frontend:
    image: vue-frontend
    build: 
      context: ./frontend/
      dockerfile: ../docker-images/vue-frontend/Dockerfile
      args:
        VITE_API_BASE_URL: 'http://${LUMEN_HOST:-localhost}:${LUMEN_PORT:-8080}'
    ports:
      - '${APP_PORT:-3000}:80'
    command: nginx -g "daemon off;"
    networks:
      - mynetwork

  # DATABASE
  mariadb:
    image: "mariadb:latest"
    volumes:
     - db_data:/var/lib/mysql
     - ./lumen-backend/database/schema/:/docker-entrypoint-initdb.d/:ro
    ports:
       - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 1
      MARIADB_DATABASE: '${LUMEN_DB_DATABASE:-mydb}'
      MARIADB_USER: '${LUMEN_DB_USERNAME:-user}'
      MARIADB_PASSWORD: '${LUMEN_DB_PASSWORD:-password}'
    networks:
      - mynetwork

  # PROXY
  proxy:
    build:
      context: ./docker-images/proxy
    image: proxy
    restart: unless-stopped
    container_name: proxy
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - ${APP_PORT}:80
      - ${APP_PORT_SSL}:443
    networks:
      - mynetwork

volumes:
  db_data:

networks:
  mynetwork:
    name: mynetwork